version: '2'

services:

  project-clara-angular:
    build:
      context: ./project-clara-client
      dockerfile: ./.docker/project-clara-angular.development.dockerfile
    command: ng serve --host 0.0.0.0 --port 4200
    container_name: project-clara-angular-serve-dev
    image: project-clara-angular
    networks:
      - dev-network
    ports:
      - '4200:4200'
      
  project-clara-server-mock:
    build:
      context: ./project-clara-server
      dockerfile: ./server-mock/.docker/project-clara-server-mock.development.dockerfile
    command: gradle server-mock:bootRun
    container_name: project-clara-server-mock-dev
    image: project-clara-server-mock
    networks:
      - dev-network
    ports:
      - '5000:5000'

networks:
  dev-network:
    driver: bridge
