version: '2'

services:

  project-clara-angular:
    build:
      context: ./project-clara-client
      dockerfile: ./.docker/project-clara-angular.development.dockerfile
    command: ng serve --host 0.0.0.0 --port 4200
    container_name: project-clara-angular-serve-dev
    image: project-clara-angular
    networks:
      - dev-network
    ports:
      - '4200:4200'

  sample-app:
    build:
      context: ./propelling-server/sample-app
      dockerfile: ./.docker/sample-app.development.dockerfile
    command: java -jar ./target/app.jar
    container_name: sample-app-serve-dev
    image: sample-app
    networks:
      - dev-network
    ports:
      - '9000:9000'

networks:
  dev-network:
    driver: bridge
