version: '2'

services:

  project-clara-angular:
    build:
      context: ./project-clara-client
      dockerfile: ./.docker/project-clara-angular.production.dockerfile
    command: ng build --prod --aot=false
    container_name: project-clara-angular-build-prod
    image: project-clara-angular
    networks:
      - prod-network
    volumes:
      - ./project-clara-client/dist:/home/app/project-clara/dist

  project-clara-nginx:
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/project-clara.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    container_name: project-clara-nginx-prod
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    image: nginx
    networks:
      - prod-network
    ports:
      - '8080:80'
    volumes:
      - ./project-clara-client/.docker/nginx.conf:/etc/nginx/conf.d/project-clara.template
      - ./project-clara-client/dist:/var/www/project-clara

    sample-app:
      build:
        context: ./propelling-server/sample-app
        dockerfile: ./.docker/sample-app.production.dockerfile
      command: java -jar ./target/app.jar
      container_name: sample-app-serve-prod
      image: sample-app
      networks:
        - prod-network
      ports:
        - '9000:9000'

networks:
  prod-network:
    driver: bridge
